common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: vagrant
  password: abc123$$

development:
  <<: *common
  database: omnicontacts
  # database: travelshopa_push_production

test:
  <<: *common
  database: omnicontacts_test

production:
  <<: *common
  database: omnicontacts_production