common: &common
  adapter: sqlite3
  encoding: unicode
  pool: 5

development:
  <<: *common
  database: omnicontacts
  # database: travelshopa_push_production

test:
  <<: *common
  database: omnicontacts_test

production:
  <<: *common
  database: omnicontacts_production